<?php

$page_role = [
	'docs'		=> 'docs',
	'account'	=> 'account',
	'sign-in'	=> 'sign-in',
	'terms-of-use'	=> 'terms-of-use',
	'legal-notice'	=> 'legal-notice',
];

$page_title_prefix = 'Sign a PDF for free';

$page_title_suffix = [
	'docs'		=> 'Your documents',
	'account'	=> 'Your account',
	'sign-in'	=> 'Sign in',
	'terms-of-use'	=> 'Terms of use',
	'legal-notice'	=> 'Legal notice',
];

$tr =[
	'SITE_NAME'				=> 'Sign a PDF',
	'EXPLICT_LANG'			=> 'English',
	'META.KEYWORDS'			=> 'sign, pdf',
	'META.DESCRIPTION'		=> 'Sign a PDF for free',
	'BACK'					=> 'Back',
	'CONFIRMATION'			=> 'Confirmation',
	'CANCEL'				=> 'Cancel',
	'CONFIRM'				=> 'Confirm',
	'WELCOME'				=> 'Welcome',
	'DATE_FORMAT'			=> "m/d/Y H:i:s",
	'MENU.SEND_DOCUMENT'	=> 'Send a document',
	'MENU.YOUR_DOCUMENTS'	=> 'Your documents',
	'MENU.CREATE_ACCOUNT'	=> 'Create an account',
	'MENU.UPDATE_ACCOUNT'	=> 'Modify your account',
	'MENU.CONFIRM_ACCOUNT'	=> 'Confirm your account',
	'MENU.VALIDATE_ACCOUNT'	=> 'Validate your account',
	'MENU.SIGN_IN'			=> 'Sign in',
	'MENU.TERMS_OF_USE'		=> 'Terms of use',
	'MENU.LEGAL_NOTICE'		=> 'Legal notice',
	'HOME.ADD_PDF'			=> 'Add a PDF',
	'UPLOAD.SENDING_DOC'	=> 'Sending your document',
	'UPLOAD.NOT_A_PDF'		=> 'This file is not recognized as a PDF',
	'UPLOAD.FILE_TOO_BIG'	=> 'The size of this file exceeds the allowed size (20MiB)',
	'UPLOAD.MAX_DOCS_NUMB'	=> 'The maximum number of documents has been reached, please delete some first',
	'UPLOAD.BYTES_RECEIVED'	=> 'Received',
	'UPLOAD.PREPARING_DOC'	=> 'Preparing your document...',
	'UPLOAD.BYTE_UNITS'		=> "['bytes', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB']",
	'DOCS.LIST_DOCUMENTS'	=> 'Here is the list of your documents',
	'DOCS.SEE_ALL_DOCS'		=> 'See all my documents',
	'DOCS.YOUR_DOCUMENT'	=> 'Your document',
	'DOCS.SIGN_THIS_DOC'	=> 'Sign this document',
	'DOCS.DELETE.CONFIRM'	=> 'Are you sure you want to remove this document ?',
	'ACCOUNT.CREATE_INTRO'	=> 'By creating an account you will retrieve easily your documents and your sisgnatures',
	'ACCOUNT.USER_NAME'				=> 'Name (or username)',
	'ACCOUNT.USER_NAME.PLACEHOLDER'	=> 'Your name',
	'ACCOUNT.USER_NAME.HELP'		=> 'From 4 to 24 characters',
	'ACCOUNT.USER_NAME.ERROR'		=> 'Invalid name',
	'ACCOUNT.USER_MAIL'				=> 'Email address',
	'ACCOUNT.USER_MAIL.PLACEHOLDER'	=> 'Your email address',
	'ACCOUNT.USER_MAIL.HELP'		=> 'A confirmation message will be sent to this address',
	'ACCOUNT.USER_MAIL.ERROR'		=> 'Invalid email address',
	'ACCOUNT.USER_PASS'				=> 'Password',
	'ACCOUNT.USER_PASS.PLACEHOLDER'	=> 'Your password',
	'ACCOUNT.USER_PASS.HELP'		=> 'From 4 to 24 characters',
	'ACCOUNT.USER_PASS.ERROR'		=> 'Invalid password',
	'ACCOUNT.CONFIRM'				=> 'Confirmation',
	'ACCOUNT.CONFIRM.PLACEHOLDER'	=> 'Your confirmation',
	'ACCOUNT.CONFIRM.HELP'			=> '',
	'ACCOUNT.CONFIRM.ERROR'			=> 'Invalid Confirmation',
	'ACCOUNT.USER_OPTIN'			=> "I accept to receive informations from this site",
	'ACCOUNT.USER_ACCEPT'			=> 'I accept the <a href="./terms-of-use" target="_blank" class="common">Terms of use</a>',
	'ACCOUNT.USER_ACCEPT.ERROR'		=> 'You must accept the terms of use',
	'ACCOUNT.UNEXPECTED_ERROR'		=> 'Unexpected error',
	'ACCOUNT.EMAIL_ALREADY_EXISTS'	=> 'This address already exists',
	'ACCOUNT.NAME_ALREADY_EXISTS'	=> 'This name already exists',
	'ACCOUNT.VALIDATION_ERROR'		=> 'The parameters are wrong',
	'ACCOUNT.ALREADY_VALIDATED'		=> 'Your account has already been validated',
	'ACCOUNT.SIGN_IN_INTRO'			=> '',
	'ACCOUNT.LOGIN_ERROR'			=> 'Incorrect identifiers',
	'ACCOUNT_YOUR_ACCOUNT'			=> 'Your account',
];
