<?php

$page_role = [
	'docs'		=> 'docs',
	'account' 	=> 'compte',
	'sign-in'	=> 'se-connecter',
	'sign-out'	=> 'se-deconnecter',
	'terms-of-use'	=> 'conditions',
	'legal-notice'	=> 'mentions-legales',
];

$page_title_prefix = 'Signer un PDF gratuitement';

$page_title_suffix = [
	'docs'		=> 'Vos documents',
	'account'	=> 'Votre compte',
	'sign-in'	=> 'Se connecter',
	'sign-out'	=> 'Sign out',
	'terms-of-use'	=> "Conditions générales d'utilisation",
	'legal-notice'	=> 'Mentions légales',
];

$tr =[
	'SITE_NAME'				=> 'Signer un PDF',
	'EXPLICT_LANG'			=> 'Français',
	'META.KEYWORDS'			=> 'signer, pdf, gratuit',
	'META.DESCRIPTION'		=> 'Signer un PDF gratuitement',
	'BACK'					=> 'Retour',
	'CONFIRMATION'			=> 'Confirmation',
	'CANCEL'				=> 'Annuler',
	'CONFIRM'				=> 'Confirmer',
	'WELCOME'				=> 'Bienvenue',
	'SUBMIT'				=> 'Valider',
	'DATE_FORMAT'			=> "d/m/Y H:i:s",
	'MENU.SEND_DOCUMENT'	=> 'Envoyer un document',
	'MENU.YOUR_DOCUMENTS'	=> 'Vos documents',
	'MENU.YOUR_SIGNATURES'	=> 'Vos signatures',
	'MENU.CREATE_ACCOUNT'	=> 'Créer un compte',
	'MENU.UPDATE_ACCOUNT'	=> 'Modifier votre compte',
	'MENU.SIGN_IN'			=> 'Se connecter',
	'MENU.SIGN_OUT'			=> 'Se déconnecter',
	'MENU.TERMS_OF_USE'		=> "Conditions générales d'utilisation",
	'MENU.YOUR_ACCOUNT'		=> 'Votre compte',
	'MENU.LEGAL_NOTICE'		=> 'Mentions légales',
	'HOME.ADD_PDF'			=> 'Ajouter un PDF',
	'UPLOAD.SENDING_DOC'	=> 'Envoi de votre document',
	'UPLOAD.NOT_A_PDF'		=> "Ce fichier n\\'est pas reconnu comme un PDF",
	'UPLOAD.FILE_TOO_BIG'	=> 'La taille de ce fichier est au-delà de la taille autorisée (20Mo)',
	'UPLOAD.MAX_DOCS_NUMB'	=> "Le nombre maximum de documents a été atteint, veuillez en supprimer d'abord",
	'UPLOAD.BYTES_RECEIVED'	=> 'Reçu',
	'UPLOAD.PREPARING_DOC'	=> 'Préparation de votre document...',
	'UPLOAD.BYTE_UNITS'		=> "['octets', 'Ko', 'Mo', 'Go', 'To', 'Po', 'Eo', 'Zo', 'Yo']",
	'DOCS.LIST_DOCUMENTS'	=> 'Ici se trouve la liste de vos documents',
	'DOCS.SEE_ALL_DOCS'		=> 'Voir tous mes documents',
	'DOCS.YOUR_DOCUMENT'	=> 'Votre document',
	'DOCS.SIGN_THIS_DOC'	=> 'Signer ce document',
	'DOCS.DELETE.CONFIRM'	=> 'Êtes-vous sûr de vouloir supprimer ce document ?',
	'ACCOUNT.CREATE_INTRO'	=> 'En créant un compte vous pourrez retrouver facilement vos documents et vos sisgnatures',
	'ACCOUNT.UPDATE_INTRO'	=> 'Vous pouvez ici modifier facilement votre compte',
	'ACCOUNT.USER_NAME'				=> 'Nom (ou pseudo)',
	'ACCOUNT.USER_NAME.PLACEHOLDER'	=> 'Votre nom',
	'ACCOUNT.USER_NAME.HELP'		=> 'De 4 à 24 caractères',
	'ACCOUNT.USER_NAME.ERROR'		=> 'Nom invalide',
	'ACCOUNT.USER_MAIL'				=> 'Adresse mail',
	'ACCOUNT.USER_MAIL.PLACEHOLDER'	=> 'Votre addresse mail',
	'ACCOUNT.USER_MAIL.HELP'		=> 'Un message de confirmation sera envoyé à cette adresse',
	'ACCOUNT.USER_MAIL.ERROR'		=> 'Adresse mail invalide',
	'ACCOUNT.USER_PASS'				=> 'Mot de passe',
	'ACCOUNT.USER_PASS.PLACEHOLDER'	=> 'Votre mot de passe',
	'ACCOUNT.USER_PASS.HELP'		=> 'De 4 à 24 caractères',
	'ACCOUNT.USER_PASS.ERROR'		=> 'Mot de passe invalide',
	'ACCOUNT.CONFIRM'				=> 'Confirmation',
	'ACCOUNT.CONFIRM.PLACEHOLDER'	=> 'Votre confirmation',
	'ACCOUNT.CONFIRM.HELP'			=> '',
	'ACCOUNT.CONFIRM.ERROR'			=> 'Confirmation invalide',
	'ACCOUNT.USER_OPTIN'			=> "J'accepte de recevoir des informations de ce site",
	'ACCOUNT.USER_ACCEPT'			=> 'J\'accepte les <a href="./terms-of-use" target="_blank" class="common">conditions générales d\'utilisation',
	'ACCOUNT.USER_ACCEPT.ERROR'		=> "Vous devez accepter les conditions",
	'ACCOUNT.UNEXPECTED_ERROR'		=> 'Erreur inattendue',
	'ACCOUNT.EMAIL_ALREADY_EXISTS'	=> 'Cette adresse existe déjà',
	'ACCOUNT.NAME_ALREADY_EXISTS'	=> 'Ce nom existe déjà',
	'ACCOUNT.VALIDATION_ERROR'		=> 'Les paramètres sont erronés',
	'ACCOUNT.ALREADY_VALIDATED'		=> 'Votre compte a déjà été validé',
	'ACCOUNT.SIGN_IN_INTRO'			=> '',
	'ACCOUNT.LOGIN_ERROR'			=> 'Identifiants incorrects',
	'ACCOUNT.DELETE.CONFIRM'		=> 'Êtes-vous sûr de vouloir supprimer ce compte ?',
	'ACCOUNT.CONFIRM_TITLE'			=> 'Confirmer votre compte',
	'ACCOUNT.CONFIRM_WELCOME'		=> "Bienvenue <b>%%user_name%%</b> ! Un message vient d'être envoyé à l'adresse <b>%%user_email%%</b>",
	'ACCOUNT.VALIDATION_TITLE'		=> 'Validation de votre compte',
	'ACCOUNT.VALIDATION_WELCOME'	=> "Merci d'avoir créé un compte ! Vous êtes maintenant connecté.",
	'ACCOUNT.UPDATE_WELCOME'		=> "Merci <b>%%user_name%%</b> ! Un message vient d'être envoyé à l'adresse <b>%%user_email%%</b>",
];
